# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference
#
version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
    ignore:
        - dependency-name: "tackler-rs"
        - dependency-name: "tackler-api"
        - dependency-name: "tackler-core"
        - dependency-name: "tackler-cli"
    rebase-strategy: "disabled"

