image:https://github.com/e257-fi/tackler-ng/actions/workflows/build.yml/badge.svg["build status", link="https://github.com/e257-fi/tackler-ng/actions"]
image:https://img.shields.io/github/v/release/e257-fi/tackler-ng?include_prereleases&color=%230868da["Github Release", link="https://github.com/e257-fi/tackler-ng/releases"]
image:https://tackler.e257.fi/img/tackler-ng.svg["crates.io: tackler", link="https://crates.io/crates/tackler"]
image:https://tackler.e257.fi/img/badge-matrix.svg["matrix: tackler", link="https://matrix.to/#/#tackler:matrix.org"]
image:https://img.shields.io/badge/tackler-documentation-%23ffcb00["Tackler Docs", link="https://tackler.e257.fi/docs"]

= Tackler-NG

Tackler-NG is rusty version of link:https://tackler.e257.fi/[Tackler].

And what is Tackler? Tackler is an accounting engine and reporting tool for
link:http://plaintextaccounting.org/[text based double-entry accounting] records.

See link:https://tackler.e257.fi/[Tackler's website] for more information about Tackler and its usage.

[NOTE]
====
Tackler Ain't Calculator and Kernel for link:http://ledger-cli.org/[Ledger] Equivalent Records. +
Why not? -- Because it uses simplified Ledger syntax.
====

== Project Status

The rusty Tackler-NG is in feature parity with old scala based Tackler CLI.

Especially the link:https://tackler.e257.fi/docs/journal/format/[Tackler Journal Format] is fully
supported, and also all transaction storage backends are supported.

 * link:https://tackler.e257.fi/docs/usage/#storage-selector[Filesystem]
 * link:https://tackler.e257.fi/docs/journal/git-storage/[Git Storage]

See `tackler --help` and link:examples/tackler.toml[Tackler Configuration] how to use these.


All reports and exports are supported:

* Reports
  ** link:https://tackler.e257.fi/docs/report-balance/[Balance]
  ** link:https://tackler.e257.fi/docs/report-balance-group/[Balance Group]
  ** link:https://tackler.e257.fi/docs/report-register/[Register]
* Exports
  ** link:https://tackler.e257.fi/docs/export-equity/[Equity]
  ** link:https://tackler.e257.fi/docs/export-equity/[Identity]

Other supported notable features are:

* Handling link:https://tackler.e257.fi/docs/commodities/[Commodities] and link:https://tackler.e257.fi/docs/currencies/[Shares]
* link:https://tackler.e257.fi/docs/txn-filters/[Transaction Filters]
* link:https://tackler.e257.fi/docs/gis/txn-geo-location[Transacation Geo Location] and link:https://tackler.e257.fi/docs/gis/txn-geo-filters/[Transaction Geo Filters]


[IMPORTANT]
====
**AS THIS IS TECHNOLOGY PREVIEW RELEASE, THERE COULD BE MISSING FEATURES
AND INCONSISTENCIES WITH EXISTING TACKLER IMPLEMENTATION.**
====


== How to build Tackler CLI application

To build rusty Tackler, you will need git and Rust installed on your environment.

If you don't have Rust installed in your system, get it:

----
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
----


Then get the source code and test vectors:

----
git clone --recurse-submodules https://github.com/e257-fi/tackler-ng
----

And build the Tackler binary:

----
cd tackler-ng

# Check the latest relase version
git tag -l

# Get the release, e.g. v24.11.0
git checkout v24.11.0

# Build tackler
cargo build --release --locked --bin tackler
----

The tackler binary will be located at `target/release/tackler`. You can try it following way:

----
target/release/tackler --config examples/simple.toml

----


You can check the source code and version info of tackler by running:

----
target/release/tackler --version
----


See `tackler --help`, link:examples/tackler.toml[full Tackler configuration file], example link:docs/examples.adoc[commands] and link:tackler-cli/CRATES.md[Tackler CLI documentation]how to use the rusty version of tackler.

link:docs/devel/readme.adoc[Developer's Guides] have technical information about Tackler-NG.

For general information about Tackler, see the original link:https://tackler.e257.fi/docs/[Tackler Documentation].

== Credits

See link:CREDITS.adoc[CREDITS] for full list of credits.


== Security

If you find a security issue in Tackler-NG, please report it as outlined in
link:./SECURITY.md[Security Policy].


== License

....
Copyright 2016-2024 E257.FI Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
....
