image:https://github.com/e257-fi/tackler-ng/actions/workflows/ci.yml/badge.svg["ci status", link="https://github.com/e257-fi/tackler-ng/actions"]
image:https://img.shields.io/github/v/release/e257-fi/tackler-ng?include_prereleases&color=%230868da["Github Release", link="https://github.com/e257-fi/tackler-ng/releases"]
image:https://tackler.e257.fi/img/badge-crates.svg["crates.io: tackler", link="https://crates.io/crates/tackler"]
image:https://img.shields.io/badge/tackler-documentation-%23ffcb00["Tackler Docs", link="https://tackler.e257.fi/docs"]
image:https://img.shields.io/github/discussions/e257-fi/tackler-ng["GitHub Discussions", link="https://github.com/e257-fi/tackler-ng/discussions"]
image:https://tackler.e257.fi/img/badge-matrix.svg["matrix: tackler", link="https://matrix.to/#/#tackler:matrix.org"]

= Tackler-NG

Tackler is fast, reliable bookkeeping engine with native
GIT SCM support for plain text accounting written in rust.
Tackler-NG is rusty version of link:https://tackler.e257.fi/[Tackler].

== Project Status

The rusty Tackler-NG is in link:https://tackler.e257.fi/features/[feature] parity with the old scala based Tackler CLI,
and this will be the basis of all future Tackler development.

[NOTE]
====
*Tackler-NG is tested with 284 of tackler's test vectors at the moment*
====

All Tackler CLI functionality is supported, including
link:https://tackler.e257.fi/docs/journal/format/[Tackler Journal Format],
transaction storages (link:https://tackler.e257.fi/docs/usage/#storage-selector[Filesystem],
link:https://tackler.e257.fi/docs/journal/git-storage/[Git SCM]),
all reports
(link:https://tackler.e257.fi/docs/report-balance/[Balance],
link:https://tackler.e257.fi/docs/report-balance-group/[Balance Group],
link:https://tackler.e257.fi/docs/report-register/[Register])
and all exports
(link:https://tackler.e257.fi/docs/export-equity/[Equity],
link:https://tackler.e257.fi/docs/export-equity/[Identity]).

Other notable features are:

* Handling link:https://tackler.e257.fi/docs/commodities/[Commodities] and link:https://tackler.e257.fi/docs/currencies/[Shares]
* link:https://tackler.e257.fi/docs/txn-filters/[Transaction Filters] for powerfull selectors of accounting data
* Accounting based on link:https://tackler.e257.fi/docs/gis/txn-geo-location[Geo Location] and link:https://tackler.e257.fi/docs/gis/txn-geo-filters/[Transaction GIS Filters]

See `tackler --help`, link:https://tackler.e257.fi/docs/[Documentation] and  link:examples/tackler.toml[Tackler Configuration] how to use tackler-ng.


== How to build Tackler CLI application

To build rusty Tackler, you will need git and Rust installed on your environment.

If you don't have Rust, install it, e.g. by running:

----
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
----


Then get the source code and test vectors:

----
git clone --recurse-submodules https://github.com/e257-fi/tackler-ng
----

And build the Tackler binary:

----
cd tackler-ng

# The main branch should build and pass all tests.
# To build a release, check relased versions:
git tag -l

# Get the release, e.g. v24.11.2
git checkout v24.11.2

# Build tackler
cargo build --release --locked --bin tackler

# the binary is located at 'target/release/tackler'
----

=== Simple example with Filesystem Journal

----
target/release/tackler --config examples/simple.toml
----

=== Complex example with Git Storage and Audit mode

Audit example uses Git SCM as journal storage, and strict and audit modes are activated by configuration.

----
target/release/tackler --config examples/audit.toml
----

Audit test data has a branch with 100_000 transactions, this query will execute in few seconds:

----
target/release/tackler \
   --config examples/audit.toml \
   --input.git.ref txns-1E5
----



See `tackler --help`, link:examples/tackler.toml[Tackler configuration] file, example link:docs/examples.adoc[commands] and link:tackler-cli/CRATES.md[Tackler CLI documentation] how to use the rusty version of tackler.

link:docs/devel/readme.adoc[Developer's Guides] have technical information about Tackler-NG. For the general information about Tackler, see the link:https://tackler.e257.fi/docs/[Tackler site].

== Credits

Special thanks to the Rust community for the all help and advice,
without forgetting Clippy.
link:https://github.com/GitoxideLabs/gitoxide[Gitoxide]
is one of the key components which made Tackler-NG possible - Thank you!

See link:CREDITS.adoc[CREDITS] for full details.


== Security

If you find a security issue in Tackler-NG, please report it as outlined in
the link:./SECURITY.md[Security Policy].


== License

....
Copyright 2016-2024 E257.FI Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
....
