# vim: tabstop=4 shiftwidth=4 softtabstop=4 smarttab expandtab autoindent
#
# This is the Chart of Accounts
#

accounts = [
    "Income",
    "Income:Lottery",
    "Expenses",
    "Expenses:ice_cream",
    "Expenses:jäätelö",
    "Expenses:jäätelö:mansikka-vadelma",
    "Expenses:crème·glacée",
    "Expenses:мороженое",
    "Expenses:アイスクリーム",
    "Expenses:風:空",
    "Assets",
    "Assets:Banks:Acme_Inc",
    "Assets:Cash",
    "Credit·Card:1234567890"
]
