[kernel]
strict = true

[kernel.timestamp]
default-time = 00:00:00

[kernel.timestamp.timezone]
name = "Europe/Helsinki"
#offset = "-07:00"

[kernel.audit]
hash = "sha-256"
mode = true

[kernel.input]
storage = "fs"

[kernel.input.fs]
dir = "txns"
glob = "**.txn"

[kernel.input.git]
repository = "tackler-data.git"
ref = "main"
dir = "txns"
suffix = ".txn"

[transaction.accounts]
file = "accounts.toml"

[transaction.commodities]
file = "commodities.toml"

[transaction.tags]
file = "tags.toml"

[report]
report-timezone = "Europe/Helsinki"
types = [ "balance", "balance-group", "register", "equity", "identity" ]
formats = [ "txt", "json" ]
accounts = [ ]
###
### Scale Settings for Reports
###
# todo: scale in action
scale = { min = 2, max = 7 }


###
### Balance Report
###
[report.balance]
title = "Balance Report"
accounts = [ ]

###
### Balance Group Report
###
[report.balance-group]
title = "Balance Group Report"
### Group by criteria
###
### Group by balances based on criteria.
### Criteria could be:
###   "year", "month", "date", "iso-week", "iso-week-date"
group-by = "month"
accounts = [ ]

###
### Register Report
###
[report.register]
title = "Register Report"
### Timestamp style
###
### This set how timestamps are displayed with register report
### See also 'timezone', 'report-timezone' options.
###
### Valid values are: date, seconds, full
###   date:    only date part is displayed (this is default)
###   seconds: date and time is displayed (up to seconds)
###   full:    date and time is displayed (up to nanoseconds)
timestamp-style = "seconds"
accounts = [ "^e:ey2016" ]
