# vim: tabstop=4 shiftwidth=4 softtabstop=4 smarttab expandtab autoindent
[kernel]
#strict = true
strict = false

[kernel.timestamp]
default-time = 12:12:12

[kernel.timestamp.timezone]
name = "Europe/Helsinki"
#offset = "-07:00"

[kernel.audit]
hash = "SHA-256"
mode = false

[transaction.accounts]
file = "accounts.toml"

[transaction.commodities]
file = "commodities.toml"

[transaction.tags]
file = "tags.toml"
