# vim: tabstop=4 shiftwidth=4 softtabstop=4 smarttab expandtab autoindent
[kernel]
#strict = true
strict = false

[kernel.timestamp]
default-time = 12:13:14

[kernel.timestamp.timezone]
name = "Europe/Helsinki"
#offset = "-07:00"

[kernel.audit]
hash = "SHA-256"
mode = false

[kernel.input]
#storage = "fs"
storage = "git"
fs = { dir = "../suite/parser/ok/txns", glob = "txn" }
git = { repo = "../suite/audit/audit-repo.git", ref = "txns-1E2", dir = "txns", suffix = "txn" }


[transaction.accounts]
file = "accounts.toml"

[transaction.commodities]
file = "commodities.toml"

[transaction.tags]
file = "tags.toml"
