= Tackler performance test setup

This directory contains tools and reference results for Tackler's performance testing.

See link:https://tackler.e257.fi/docs/performance/[Description of Performance]
for explanation of generated artificial test data.

It is recommemded to put the perf data directory outside of Tackler project directory.  
If 1E5-1E6 data sets are inside project's directory, your IDE might go nuts while it scans new files.


== Results

Tools to run perf tests are located in link:./bin[bin].

* xref:./results/perf-hw02.adoc[HW02 results]


== Test data

Test data is generated with 
link:https://gitlab.com/e257/accounting/tackler/-/tree/main/tools/generator[generator tool], 
version: 0.5.2


File count of test sets:
----
$ for ds in perf-1E?; do echo -n "$ds: "; find $ds -type f | wc -l; done
perf-1E1: 10
perf-1E2: 100
perf-1E3: 1000
perf-1E4: 10000
perf-1E5: 100000
perf-1E6: 1000000
----

Actual data size of test sets:
----
$ for ds in perf-1E?; do echo -n "$ds: "; (find $ds -type f | xargs cat ) | wc -c; done
perf-1E1:       1_358
perf-1E2:      13_664
perf-1E3:     137_598
perf-1E4:   1_385_945
perf-1E5:  13_959_367
perf-1E6: 140_587_889
----

Size on disk for test sets:
----
perf-1E1    128K
perf-1E2    856K
perf-1E3    5.4M
perf-1E4     41M
perf-1E5    398M
perf-1E6    3.9G
----

=== Git perf test repository

Size of bare test data repository: 201M


== Possible layout for perf test data

Content of `perf-test` directory, next to the `tackler`'s toplevel directory:

----
bin 		   	-> ../tackler-ng/perf/bin/
perf.toml 	   	-> ../tackler-ng/perf/perf.toml
perf-accounts.toml 	-> ../tackler-ng/perf/perf-accounts.toml
perf-commodities.toml 	-> ../tackler-ng/perf/perf-commodities.toml
results 	   	-> ../tackler-ng/perf/results
data 			== perf data
----

