### Configuration settings for Tackler-NG
###
### See tackler.toml file full configuration options
### and documentation.
###
### The format of this file is TOML (https://toml.io/en/)
[kernel]
strict = true
audit = { mode = true, hash = "SHA-256" }
timestamp = { default-time = 00:00:00, timezone = { name = "UTC" } }

input = { storage = "git", git = { repository = "../suite/audit/audit-repo.git", dir = "txns", ref = "txns-1E1", suffix = "txn" } }

[transaction]
accounts    = { path = "audit/accounts.toml" }
commodities = { path = "audit/commodities.toml" }
tags        = { path = "none" }


### Report Configuration
[report]
report-timezone = "UTC"
scale = { min = 2, max = 4 }
accounts = [ "^a:.*" ]
targets = [ "balance" ]

balance       = { title = "Balance Report" }
balance-group = { title = "Balance Group Report", group-by = "month" }
register      = { title = "Register Report", accounts = [ "^e:", "^a:" ]}


### Export Configuration
[export]
equity = { accounts = [ "^a:", ], equity-account = "Equity:Balance" }
