###
### Solar: Solar Energy Value example (price functionality)
###        This uses Variable Market Value ("txn-time") feature
###
[kernel]
strict = false
audit = { mode = false, hash = "SHA-256" }
timestamp = { default-time = 00:00:00, timezone = { name = "Europe/Helsinki" } }

input = { storage = "fs", fs = { path = "solar", dir = "txns", suffix = "txn" } }

[price]
db-path = "solar/txns/se-used.db"
lookup-type = "txn-time"

[transaction]
accounts    = { path = "none" }
commodities = { path = "none" }
tags        = { path = "none" }


### Report Configuration
[report]
report-timezone = "Europe/Helsinki"
scale = { min = 2, max = 2 }
targets = [ "balance", "register" ]
commodity = "c" # Euro cent
accounts = [ "SolarPanels:Array:.*" ]

balance       = { title = "Balance Report" }
balance-group = { title = "Balance Group Report", group-by = "month" }
register      = { title = "Register Report", timestamp-style = "seconds" }


### Export Configuration
[export]
targets = [ ]
equity = { accounts = [ ], equity-account = "Equity:Balance" }
