= TEP-1015: Price data support

Add price data support for currencies, shares and commodities.

Implementation branch:
link:https://github.com/e257-fi/tackler-ng/tree/tep/tep-1015-price-data[/tep/tep-1015-price-data]

Github issue: https://github.com/e257-fi/tackler-ng/issues/36
Github PR: https://github.com/e257-fi/tackler-ng/pull/39

== Summary

Add a representation of historical price data.

* Define `pricedb` format
* Describe which entry of price data applies to which set of transactions

=== Price data application policy

1. If a posting has rate or equivalence noted, it gets applied.
2. Otherwise, price conversion only takes account of data noted in the nearest earlier entry price DB, disregarding any rate or equivalent noted in any transaction that is later than the price DB entry.
  * This is to ensure that filtering out any transaction does not change a report for a given PriceDB.

This TEP does not propose any method for calculating the fixed conversions (e.g. oz to g, gallons to litres, etc).

== Journal File Format

No change would be made to the journal file format. A new file type would be added with a format similar to the default format of Ledger CLI as described https://ledger-cli.org/doc/ledger3.html[here].

----
'P' TIMESTAMP AMOUNT COMMODITY '=' AMOUNT COMMODITY OPTIONAL_COMMENT
----

COMMENT: This should/could be just simplified ledger format?
----
'P' TIMESTAMP COMMODITY AMOUNT COMMODITY OPT_COMMENT
----

Where OPT_COMMENT is prefixed with `';' space+`, this is similar as Txn comments.

For example:
----
P 2025-01-07 EUR 1.0393 USD ; as reported by Central Bank of Europe
----

There are some existing usage for this format:

* link:https://github.com/kantord/pricedb[pricedb -project]
* link:https://hledger.org/1.41/hledger.html#p-directive[hledger P-directive]

=== Timestamp handling

The `timestamp` will use the same logic as transaction timestamps:

* RFC3339 timestamp with offset information
* Timestamp without zone or offset, then the `kernel.timestamp.timezone` value is used as zone/offset.
* Date, then `kernel.timestamp.default-time` is used with `kernel.timestamp.timezone`.

The resulting timestamp is always with zone/offset.


== Implementation

=== CLI Changes

New command line switch to activate price data, this could be implemented later.


=== CONF Changes

New configuration key for pricedb, this is similar as `accounts`, `commodidities` and `tags`

----
[transaction.pricedb]
path = "path/to/pricedb"
----

=== Filtering Changes

None

=== Machinery

Changes to machinery

* [ ] Add a new model _PriceEntry_ with fields
  - timestamp with offset or timezone (1)
  - commodity 1 with optional amount (assumed 1 if missing) (2)
  - commodity 2 with amount
  - optional comment

1) The value time (price point) could be reported (in reports), so it would be nice to have timestamp with zone/offset for user experience, if needed.  There is also `report.report-timezone` which should be used to present the price timestamp in defined timezone.

2) I would recommend that it's always 1, as that will simplify the logic and commodity 2 could be adjusted against that.

The counter-argument is if there are exchange rates with full units e.g. 2 apples for 3 oranges, but that's special case, and would need own special logic in any case.

==== API Changes

Api changes to server or client interfaces.

===== Server API Changes

Changes to server API

* [ ] item

===== Client API Changes

Changes to client API or JSON model

* [ ] item

===== JSON Model

Changes to JSON model

* [ ] Metadata
* [ ] JSON Reports
    ** [ ] BalanceReport
    ** [ ] BalanceGroupReport
    ** [ ] RegisterReport


==== New Dependencies

* [ ] link / url of new dependency
** [ ] Add and check licenses: link / url
** [ ] Is there NOTICE file(s)?
** [ ] Add license under link:../licenses/[doc/licenses]
*** [ ] Add NOTICES under link:../licenses/[doc/licenses]
** [ ] Add link of license to xref:../readme.adoc[index]
** [ ] Add link to Site credits
** [ ] Add license material to binary distribution


=== Reporting

Changes to reports or reporting

The used prices could be reported as part of the Metadata section of the report. This probably should be behind a switch, so that it can be turned off, if there are many commodities / prices to be reported.

Reporting format could be something like this
----
Git Storage
         commit : 4aa4e9797501c1aefc92f32dff30ab462dae5545
      reference : txns-1E1
      directory : txns
         suffix : .txn
        message : txns-1E1: 2016/12

Txn Set Checksum
        SHA-256 : 9b29071e1bf228cfbd31ca2b8e7263212e4b86e51cfee1e8002c9b795ab03f76
       Set size : 10

Price Data
           time : 2025-01-08 12:13:14
      commodity : EUR
          value : 1.234 USD
                -
           time : 2024-12-31 08:00:00
      commodity : He·bar_50L·tank
          value : 3.45 EUR
----

==== Balance Report

Changes to balance report

* [ ] item


==== Balance Group Report

Changes to balance group report

* [ ] item


==== Register Report

Changes to register report

* [ ] item


=== Exporting

Changes to exports or exporting

==== Equity Export

Changes to equity export

* [ ] item


==== Identity Export

Changes to identity export

* [ ] item


=== Documentation

* [ ] xref:./readme.adoc[]: Update TEP index
* [ ] xref:../../README.adoc[]: is it a new noteworthy feature?
* [ ] link:../../CHANGELOG[]: add new item
* [ ] Does it warrant own T3DB file?
** [ ] update xref:../../suite/tests.adoc[]
** [ ] update xref:../../suite/check-tests.sh[]
** [ ] Add new T3DB file link:https://github.com/e257-fi/tackler-t3db/[tests-XXXX.yml: TEP-XXXX T3DB]
* [ ] User docs
** [ ] User Manual
*** [ ] cli-arguments
**** [ ] `--arg-1`
**** [ ] `--arg-2`
** [ ] tackler.toml
*** [ ] `setting-1`
*** [ ] `setting-2`
** [ ] accounts.toml
** [ ] commodities.toml
** [ ] tags.toml
** [ ] examples
* [ ] Developer docs
** [ ] API changes
*** [ ] Server API changes
*** [ ] Client API changes
*** [ ] JSON Examples


=== Future Plans and Postponed (PP) Features

How and where to go from here?

==== Postponed (PP) Features

Anything which wasn't implemented?


=== Tests

Normal, ok-case tests to validate functionality:

* [ ] test

==== Errors

Various error cases:

* [ ] e: error test

==== Perf

Is there need to run or create new perf tests?

* [ ] perf test

==== Feature and Test Coverage Tracking



Feature-id::

* name: <Feature name / subject-line>
* uuid: <UUID>


link:https://github.com/e257-fi/tackler-t3db/[tests-XXXX.yml: TEP-XXXX T3DB]


==== Metadata template for Feature and Test Coverage Tracking

....
features:
  - feature:
      id: 98c2b696-d250-4141-bd82-c4126ec11c1d
      subject: "Price data support"

  - feature:
      id: uuid
      parent: uuid-of-parent
      subject: "todo: one-line description of sub feature"
      tests:
        errors:
          - error:
              id: uuid
              name: "todo: name of test class/method or test description file"
              desc: "todo: description"
        operations:
          - test:
              id: uuid
              name: "todo: name of test class/method or test description file"
              descriptions:
                - desc: "todo: description"
              references:
                - ref: balance
                - ref: balance-group
                - ref: register
                - ref: identity
                - ref: equity
....


'''
Tackler is distributed on an *"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND*, either express or implied.
See the link:../../LICENSE[License] for the specific language governing permissions and limitations under
the link:../../LICENSE[License].
