= TEP-1008: Numeric Account Names

Allow account names to start with numbers and/or be numeric only.

== Summary

Change Tackler Journal file format so that it will accept account names
starting with numbers and/or all numeric account names.  It would be
beneficial to support account names for Credit Cards, Bank Routing numbers,
Bank Account numbers, crypto currencies accounts and wallets, customer/employee numbers,
container ids, etc.

....
Liabilities:CreditCard:1234·4567·8900·0000
Assets:Account:123456-12345678
Address:4zefqrnuz95sw
Helium:Tank:102
....


== Journal file format

Change journal file format so that sub-account name could start
with number and/or be all numeric.  Top-account and commodities and currencies
must still start with UTF-8 letter.

Top-Account::
If top-accounts starts with utf-8 letter, it would leave more room to extend grammar
in the future (for single posting / account).

Commodities::
It would be too confusing if commodities could start with numbers, or be all numeric.

For example:
....
Expences:Ice_Cream  3 000; this is not valid syntax
Assets:Cash
....

== Implementation

=== CLI changes

None


=== CONF changes

None


=== Machinery

Changes to:

* [x] link:../devel/antlr/TxnLexer.g4[ANTLR TxnLexer]
* [x] link:../devel/antlr/TxnParser.g4[ANTLR TxnParser]
* [x] link:../devel/antlr/ctc_handler.rs[ANTLR CtxHandler]


==== API changes

None


===== Server API changes

None


===== Client API changes

None


==== New dependencies

None


=== Reporting

None


==== Balance report

None


==== Balance Group report

None


==== Register report

None


=== Exporting

Changes to exports or exporting

==== Equity export

Equity export generated by post TEP-1008 is not necessarily valid input
for pre TEP-1008 version of Tackler.


==== Identity export

Equity export generated by post TEP-1008 is not necessarily valid input
for pre TEP-1008 version of Tackler.


=== Documentation

* [x] xref:./readme.adoc[]: Update TEP index
* [x] link:../../CHANGELOG[]: add new item
* [x] Does it warrant own T3DB file?
** [x] update xref:../../tests/tests.adoc[]
** [x] update link:../../tests/check-tests.sh[]
** [x] Add new T3DB file link:../../tests/tests-1008.yml[]
* [x] User docs
** [x] journal format
** [x] accounts.conf


=== Future plans and Postponed (PP) features

How and where to go from here?

==== Postponed (PP) features

Anything which wasn't implemented?


=== Tests

Normal, ok-case tests to validate functionality:

* [x] ok accounts
** [x] `a:0`
** [x] `a:001`
** [x] `a:0_0`
** [x] `a:0-0`
** [x] `a:0·0`
** [x] `a:0:abc`
** [x] `a:001:abc`
** [x] `a:0_0:abc`
** [x] `a:0-0:abc`
** [x] `a:0·0:abc`
** [x] `a0:0`
** [x] `a0:001`
** [x] `a0:0_0`
** [x] `a0:0-0`
** [x] `a0:0·0`
** [x] `a0:001:1_2`
** [x] `a0:0_0:1-2`
** [x] `a0:0-0:1·2`
** [x] `a0:0·0:123`
** [x] `a0:001:abc`
** [x] `a0:0_0:abc`
** [x] `a0:0-0:abc`
** [x] `a0:0·0:abc`
** [x] `a:abc:001`
** [x] `a:abc:0_0`
** [x] `a:abc:0-0`
** [x] `a:abc:0·0`
** [x] `a0:abc:abc`
** [x] `a0:0123456789`
** [x] `a0:0123456789:123-456-789`
** [x] `a0:4zefqrnuz95sw`
* [x] ok commodity
** [x] `au`
** [x] `au_oz`
** [x] `au-g`
** [x] `au·kg`
** [x] `O2_bar`
** [x] `O2-bar`
** [x] `O2·bar`
** [x] `O2_bar_50L`
** [x] `O2-bar-50L`
** [x] `O2·bar·50L`
** [x] `SP500`


==== Errors

Various error cases:

* [x] e: account names with errors
** [x] `0`
** [x] `0:0`
** [x] `a:0.0`
** [x] `_0`
** [x] `_0:a`
** [x] `·0`
** [x] `·0:a`
** [x] `-0`
** [x] `a:-0:a`
** [x] `a:_0`
** [x] `a:_0:a`
** [x] `a:·0`
** [x] `a:·0:a`
** [x] `a:-0`
** [x] `a:-0:a`
* [x] e: commodity names with errors
** [x] `0coin`
** [x] `0000`
** [x] `a0.000`
** [x] `a0,000`
** [x] `au:oz`
** [x] `_0`
** [x] `·0`
** [x] `-0`


==== Perf

Is there need to run or create new perf tests?

* [x] perf test

Based on comparison between version 0.23 and tep-1008,
this change has no impact on performance.


==== Feature and Test case tracking

Feature-id:: bfc11481-21e2-4d12-8d9d-c4b434fd9228

link:https://github.com/tackler-ng/tackler-t3db/blob/main/tests-1008.yml[TEP-1008 Test Coverage]



'''
Tackler is distributed on an *"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND*, either express or implied.
See the link:../../LICENSE[License] for the specific language governing permissions and limitations under
the link:../../LICENSE[License].
