= TEP-1015: Price data support

Add price data support for currencies, shares and commodities.

Implementation branch:
link:https://github.com/e257-fi/tackler-ng/tree/tep/tep-1015-price-data[/tep/tep-1015-price-data]

Github issue: https://github.com/e257-fi/tackler-ng/issues/36
Github PR: https://github.com/e257-fi/tackler-ng/pull/39

== Summary

Add a representation of historical price data.

* Define `pricedb` format
* Describe which entry of price data applies to which set of transactions

=== Price data application policy

1. If a posting has rate or equivalence noted, it gets applied.
2. Otherwise, price conversion only takes account of data noted in the nearest earlier entry price DB, disregarding any rate or equivalent noted in any transaction that is later than the price DB entry.
  * This is to ensure that filtering out any transaction does not change a report for a given PriceDB.
  * This is also to ensure that reported values won't change over the time (see  <<historic-with-filters>>).

This TEP does not propose any method for calculating the fixed conversions (e.g. oz to g, gallons to litres, etc).

[#historic-with-filters]
==== Historic price data with filters

Let's assume there are following price data entries (three entries per year, distributed evenly):

----
P 2024-01-01 ACME 2401.01 USD
P 2024-05-01 ACME 2405.01 USD
P 2024-09-01 ACME 2409.01 USD
P 2025-01-01 ACME 2501.01 USD
----

Today is 2025-01-01 and we run filtering query which will include txns from range `2024-01-01 .. 2024-04-01` into our reports.

The used price data for reporting is 2401.01 USD, (the `P 2024-01-01 ACME 2401.01 USD` entry), as it is the nearest earlier recorded price in the Price DB.  This will ensure that reported values are same, regardless if the report is run on 2024-04-01 or 2025-01-01.


==== Inverted prices

At the moment inverted prices are not supported.

With following PriceDB, conversion from `USD` to `EUR` is not supported.

.PriceDB
----
P 2025-01-07 EUR 1.3 USD
----

For `USD` to `EUR` conversion, there must be an own entry in the price db:

.PriceDB
----
P 2025-01-07 EUR 1.3 USD
P 2025-01-07 USD 0.77 EUR ; 1/1.3 ~ 0.7692307692307692307, in real life this is official rate
----

==== Price conversion chains

Price conversions chains are not supported with the initial implementation.

For example, with following rates

.PriceDB
----
P 2025-01-07 EUR 11.50 SEK
P 2025-01-07 SEK  1.02 NOK
P 2025-01-07 NOK  0.09 USD ; EUR->SEK-NOK->USD = 1.055700. The real rate is 1.02
----

The conversion from `EUR` to `USD` via `SEK` and `NOK` is not supported.

Reason is that this substantially complicates reporting logic, and also could produce surprising results, especially when mixed with direct conversion rates.


== Journal File Format

No change would be made to the journal file format. A new file type would be added with a format similar to the default format of Ledger CLI as described https://ledger-cli.org/doc/ledger3.html[here].

----
'P' TIMESTAMP COMMODITY AMOUNT COMMODITY OPT_COMMENT
----

Where OPT_COMMENT is prefixed with `';' space+`, this is similar as Txn comments.

For example:
----
P 2025-01-07 EUR 1.0393 USD ; as reported by Central Bank of Europe
----

There are some existing usage for this format:

* link:https://github.com/kantord/pricedb[pricedb -project]
* link:https://hledger.org/1.41/hledger.html#p-directive[hledger P-directive]

=== Timestamp handling

The `timestamp` will use the same logic as transaction timestamps:

* RFC3339 timestamp with offset information
* Timestamp without zone or offset, then the `kernel.timestamp.timezone` value is used as zone/offset.
* Date, then `kernel.timestamp.default-time` is used with `kernel.timestamp.timezone`.

The resulting timestamp is always with offset.


== Implementation

=== CLI Changes

New command line switch to activate price data, this could be implemented later.


=== CONF Changes

New configuration key for pricedb, this is similar as `accounts`, `commodidities` and `tags`

----
[transaction.pricedb]
path = "path/to/pricedb"
----

=== Filtering Changes

None

=== Machinery

Changes to machinery

* [ ] Add a new model _PriceEntry_ with fields
  - timestamp with offset
  - commodity 1 with amount 1
  - commodity 2 with rate
  - optional comment

The `report.report-timezone` is used to convert price data to displayed zone in the reports.

==== API Changes

Api changes to server or client interfaces.

===== Server API Changes

Changes to server API

* [ ] item

===== Client API Changes

Changes to client API or JSON model

* [ ] item

===== JSON Model

Changes to JSON model

* [ ] Metadata
* [ ] JSON Reports
    ** [ ] BalanceReport
    ** [ ] BalanceGroupReport
    ** [ ] RegisterReport


==== New Dependencies

* [ ] link / url of new dependency
** [ ] Add and check licenses: link / url
** [ ] Is there NOTICE file(s)?
** [ ] Add license under link:../licenses/[doc/licenses]
*** [ ] Add NOTICES under link:../licenses/[doc/licenses]
** [ ] Add link of license to xref:../readme.adoc[index]
** [ ] Add link to Site credits
** [ ] Add license material to binary distribution


=== Reporting

Changes to reports or reporting

The used prices could be reported as part of the Metadata section of the report. This probably should be behind a switch, so that it can be turned off, if there are many commodities / prices to be reported.

Reporting format could be something like this
----
Git Storage
         commit : 4aa4e9797501c1aefc92f32dff30ab462dae5545
      reference : txns-1E1
      directory : txns
         suffix : .txn
        message : txns-1E1: 2016/12

Txn Set Checksum
        SHA-256 : 9b29071e1bf228cfbd31ca2b8e7263212e4b86e51cfee1e8002c9b795ab03f76
       Set size : 10

Price Data
           time : 2025-01-08 12:13:14
      commodity : EUR
          value : 1.234 USD
                -
           time : 2024-12-31 08:00:00
      commodity : He·bar_50L·tank
          value : 3.45 EUR
----

==== Balance Report

Changes to balance report

* [ ] item


==== Balance Group Report

Changes to balance group report

* [ ] item


==== Register Report

Changes to register report

* [ ] item


=== Exporting

Changes to exports or exporting

==== Equity Export

Changes to equity export

* [ ] item


==== Identity Export

Changes to identity export

* [ ] item


=== Documentation

* [ ] xref:./readme.adoc[]: Update TEP index
* [ ] xref:../../README.adoc[]: is it a new noteworthy feature?
* [ ] link:../../CHANGELOG[]: add new item
* [ ] Does it warrant own T3DB file?
** [ ] update xref:../../suite/tests.adoc[]
** [ ] update xref:../../suite/check-tests.sh[]
** [ ] Add new T3DB file link:https://github.com/e257-fi/tackler-t3db/[tests-XXXX.yml: TEP-XXXX T3DB]
* [ ] User docs
** [ ] User Manual
*** [ ] cli-arguments
**** [ ] `--arg-1`
**** [ ] `--arg-2`
** [ ] tackler.toml
*** [ ] `setting-1`
*** [ ] `setting-2`
** [ ] accounts.toml
** [ ] commodities.toml
** [ ] tags.toml
** [ ] examples
* [ ] Developer docs
** [ ] API changes
*** [ ] Server API changes
*** [ ] Client API changes
*** [ ] JSON Examples


=== Future Plans and Postponed (PP) Features

How and where to go from here?

* Maybe support for price conversion chains? (`EUR` -> `SEK` -> `NOK` -> `USD`)

[#future-price-date]
==== Used Price date

In the future there could be a CLI/CONF option to define which price data will be used with reports when using filtering and restricting reporting to past dates.

Possible idea-level options could be:

* Latest recorded value in PriceDB
* Latest available price before given date (e.g. `--price.date=2024-05-01`)
* Next, nearest future price
* Linear fitting between nearest past and nearest future prices


==== Postponed (PP) Features

Anything which wasn't implemented?


=== Tests

Normal, ok-case tests to validate functionality:

* [ ] strict-mode
    ** [x] On
    ** [ ] Off (without commodities)

* [ ] txn with empty commodities when price conv is activated

* [ ] No conversion
    ** [x] commodity but no conversion activated
    ** [ ] Secondary account with non-conv commodity (val-pos notation)

* [x] Selecting correct price by time
    ** [x] at-txn
        *** [x] too early price
        *** [x] too late price
    ** [x] last-value at pricedb
        *** [x] too early price
        *** [-] too late price
    ** [x] Filter: Txn-TS-END
        *** [x] too early price
        *** [x] too late price
        *** [ ] filter ts is after last filtered txn ts

    ** [ ] CLI/CONF: Timestamp
        *** [ ] too early price
        *** [ ] too late price
        *** [ ] timestamp is after last filtered txn ts

* [ ] Multiple sources to same target
    ** [ ] {aaa, bbb, ccc} -> TCKLR

* [ ] Multiple target commodities from same base commodity
    ** [ ] aaa -> {AAA, BBB, CCC, TCKLR}, all with matching timestamps

* [ ] postings with value positions
    ** [ ] value position for source posting
    ** [ ] value position for target posting

* [ ] Balance-Group
    ** [ ] Commodities distributed so that each Balance-Group has different conversion
        *** [ ] Conv: a -> TCKLR, b->TCKLR, etc.
        *** [ ] Conv: a -> AAA, b->BBB, etc. - is this needed?
    ** [ ] Each Balance-Group have different conversion value
        *** [ ] filter: group-selector == txn-ts-end (Is this desired behaviour?)


==== Errors

Various error cases:

* [ ] e: target commodity not found (at all) in pricedb
* [ ] e: no source to target conversion in pricedb
* [ ] e:
* [ ] e:
* [ ] e:


==== Perf

Is there need to run or create new perf tests?

* [ ] perf test

==== Feature and Test Coverage Tracking



Feature-id::

* name: <Feature name / subject-line>
* uuid: <UUID>


link:https://github.com/e257-fi/tackler-t3db/[tests-XXXX.yml: TEP-XXXX T3DB]


==== Metadata template for Feature and Test Coverage Tracking

[source,yaml]
....
features:
  - feature:
      id: 98c2b696-d250-4141-bd82-c4126ec11c1d
      subject: "Price data support"

  - feature:
      id:4d6f0dac-c202-45f4-9b95-7682d6c8df94
      parent: 98c2b696-d250-4141-bd82-c4126ec11c1d
      subject: "Price conversions"
      tests:
        errors:
          - error:
              id: uuid
              name: "todo: name of test class/method or test description file"
              desc: "todo: description"
        operations:
          - test:
              id: 7cbe3cb4-1b23-44bb-8e5e-ba2c8991e589
              name: "price/ok/price.sh: price-00"
              descriptions:
                - desc: "No conversion"
              references:
                - ref: balance
                - ref: balance-group
                - ref: register
                - ref: identity
                - ref: equity
          - test:
              id: 6ddcb0d4-7dc6-4909-a1b4-ecbb5a33a186
              name: "price/ok/price.sh: price-01"
              descriptions:
                - desc: "conv: at-txn"
              references:
                - ref: balance
                - ref: balance-group
                - ref: register
                - ref: identity
                - ref: equity
          - test:
              id: af19f8e7-a6f2-4f64-8c5a-b774dba4f58c
              name: "price/ok/price.sh: price-02"
              descriptions:
                - desc: "conv: last-value at price-db"
              references:
                - ref: balance
                - ref: balance-group
                - ref: register
                - ref: identity
                - ref: equity
          - test:
              id: 4075e741-605b-4e67-ab7d-0d13f38956ca
              name: "price/ok/price.sh: price-03"
              descriptions:
                - desc: "conv: filter: txn-ts-end"
              references:
                - ref: balance
                - ref: balance-group
                - ref: register
                - ref: identity
                - ref: equity
          - test:
              id: 0c600957-5c15-42d0-9bb9-b618ad7d597f
              name: "price/ok/price.sh: price-04"
              descriptions:
                - desc: "conv: filter: txn-ts-end > last txn-ts"
              references:
                - ref: balance
                - ref: balance-group
                - ref: register
                - ref: identity
                - ref: equity
          - test:
              id: 39c60c8b-b999-4305-8c57-5c06e99cc919
              name: "price/ok/price.sh: price-05"
              descriptions:
                - desc: "conv: Timestamp"
              references:
                - ref: balance
                - ref: balance-group
                - ref: register
                - ref: identity
                - ref: equity
          - test:
              id: f7211562-c69d-4bab-a768-65b15803efdf
              name: "price/ok/price.sh: price-06"
              descriptions:
                - desc: "conv: timestamp > last txn-ts"
              references:
                - ref: balance
                - ref: balance-group
                - ref: register
                - ref: identity
                - ref: equity
          - test:
              id:
              name: "price/ok/price.sh: price-"
              descriptions:
                - desc: "todo: description"
              references:
                - ref: balance
                - ref: balance-group
                - ref: register
                - ref: identity
                - ref: equity
....


'''
Tackler is distributed on an *"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND*, either express or implied.
See the link:../../LICENSE[License] for the specific language governing permissions and limitations under
the link:../../LICENSE[License].
