
name: ci

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfrmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - run: rustup toolchain install nightly-x86_64-unknown-linux-gnu
      - run: rustup component add --toolchain nightly-x86_64-unknown-linux-gnu rustfmt
      - run: rustup show
      - uses: Swatinem/rust-cache@v2
      - run: cargo +nightly fmt --all --check  -- --style-edition 2024

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - run: rustup show
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --workspace --all-targets --no-deps -- -D warnings
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - run: rustup show
      - uses: Swatinem/rust-cache@v2
      - run: cargo test
  
  test-suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - run: rustup show
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --release
      - run: target/release/tackler --version
      - run: target/release/tackler --config examples/simple.toml
      - run: target/release/tackler --config examples/audit.toml
      - run: tests/sh/test-runner-ng.sh

